### ISSUE TITLE
Add my widget

### ISSUE THREAD

**Issue by TokkiHeikkila** [StreamUPTips/obs-streamup#2]
Hello, I want to add my widget. How can I configure it to install via streamup :)

**Comment by XSilverlink** [comment]
Can you specify a little bit more what you are asking?

**Comment by TokkiHeikkila** [comment]
The streamup site has widgets that can be imported using the plugin. Can I use the plugin functionality so that a person can import the widget I created? I found a file with the .streamup extension, but I have no idea how to set it up.

sorry for my english, this is google translate

**Comment by XSilverlink** [comment]
Sorry, but the extension is created for our own Streamup OBS Scenes, it has a specific way of setting stuff and things up. If you want to simply paste a scene I would recommend using [Exeldro's Source Copy](https://obsproject.com/forum/resources/source-copy.1261/)
