### ISSUE TITLE
Kudos, Questions, and a Request

### ISSUE THREAD

**Issue by scotthardwick** [StreamUPTips/obs-streamup#4]
Kudos: First and most importantly, WOW and THANK YOU for creating something to make it easier to check that OBS plugins have updates. I am not a "traditional" streamer and only use OBS a few times a year for work projects and so every time I crank it up, obviously a lot changes between my uses.  Finally this makes it easy to figure out where to start with updates!

Questions: Am I correct that not all plugins currently existing are registered and/or have a way for this plugin to know if they are out of date?  I noticed that it doesn't seem to know about the Virtual Cam Filter, StreamDeck, DroidCam, and WinCaptureAudio plugins.

Request: This plugin lets us easily click the name of the out of date plugin and it downloads the appropriate update files.  Would there be some way to also let us click to go to the appropriate update page on the OBS site to see what has been updated between our version and the latest version? Just a thought.

Bravo and Thanks!

**Comment by andilippi** [comment]
Hey Scott!

Thank you for those kind words. I always want to do my best, it takes a little while for me to do things as i'm a very developer.

This has been brought to my attention and will be looking into it soon to add two links, one for the forum page and a direct one.

I can only support plugins that have had a version number sent to the log file when they are loaded so usually older plugins aren't supported. I do keep updating our database manually so as soon as any new plugins come out or are updated i will add them :)

Cheers
