### ISSUE TITLE
Support plugins with version numbers consisting of more or less than 3 components

### ISSUE THREAD

**Issue by YorVeX** [StreamUPTips/obs-streamup#5]
For example "1.0" or "1.0.0.1234" instead of "1.0.0".

I know that [semantic versioning](https://semver.org/) is the most used standard, but still a system with only 2 components is also relatively widespread for smaller and simpler products. And even semantic versioning would allow for a 4th component so that should be supported too (I don't know whether it currently is, I just thought I'd also note that here while at it):
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

Also it doesn't seem that you currently require semantic versioning explicitly anyway, readme only says:
> They just need to add their plugin name and version number to the Log file upon load.

Two of my plugins use 2 component versioning, because there I don't expect to release a lot of versions anyway, adding a third item just wouldn't make sense to me.
I can see that they are in your database with the correct search string, but StreamUP doesn't detect necessary updates for them. It also doesn't list them as incompatible under "Installed Plugins", they just don't appear at all.

Another plugin of mine that has a 3 component version number is supported just fine.

![image](https://github.com/StreamUPTips/obs-streamup/assets/528974/cce7201f-4139-4a48-a85d-ee6804893f92)

**Comment by andilippi** [comment]
Hey dude!! I actually saw your comment when the plugin was "accidentally" accepted onto the OBS forums.

I actually thought i had patched this but it must have past me by. Originally it definitely did work with your plugins but then fat fingers here must have broke it LOL!

Thanks for bringing it to my attention. I'm a very new developer with 0 experience, so bare with. <3
